### PR TITLE
bblayers.conf: add meta-tpm layer

### PR DESCRIPTION
**Pull request by fboudra**

### CODE REVIEW

**Comment by fboudra** [comment]
@sergioprado @rborn-tx @jsrc27 following up https://github.com/toradex/meta-toradex-security/commit/8b530526ebd130db0c099882bb6752c68e3948eb

How could that work in torizon without adding meta-tpm layer, which provides tpm2-tools and tpm2-tss?

Also it requires another update:
`Recipe tpm2-tss, package tpm2-tss: system username "tss" does not have a static ID defined. Add tss to one of these files: layers/meta-toradex-torizon/files/torizon-static-passwd`

**Comment by fboudra** [comment]
fwiw, fTPM works for me with Torizon (tried torizon-docker), once I
- added meta-tpm layer to bblayers.conf
- added "tpm2" to DISTRO_FEATURES
- added "tss" to torizon-static-passwd and torizon-static-group

**Comment by sergioprado** [comment]
@fboudra Thanks for reporting! Do you know why you had to add "tpm2" to DISTRO_FEATURES?

**Comment by fboudra** [comment]
@sergioprado Initially, I added it in DISTRO_FEATURES because of meta-tpm sanity check:
https://git.yoctoproject.org/meta-security/tree/meta-tpm/classes/sanity-meta-tpm.bbclass?h=scarthgap

Hence I had this warning message:
```
WARNING: You have included the meta-tpm layer, but 'tpm or tpm2' has not been enabled in your DISTRO_FEATURES. Some bbappend files and preferred version setting may not take effect. See the meta-tpm README for details on enabling tpm support.
```

after double checking, it looks like I don't need to add "tpm2" explicitley in DISTRO_FEATURES because it was already set by my verdin-imx8mp machine config with MACHINE_FEATURES.

**Comment by sergioprado** [comment]
> Initially, I added it in DISTRO_FEATURES because of meta-tpm sanity check:

Understood, thanks for clarifying. I will investigate if it makes sense to add `tpm2` to DISTRO_FEATURES in `meta-toradex-security`.

**Comment by fboudra** [comment]
related fix: https://github.com/torizon/meta-toradex-torizon/commit/f614a5a7cb824814e6c99d9163ee29367afb3913

**Comment by rborn-tx** [comment]
@sergioprado I imagine we can close this given the fix already referenced by @fboudra, right? Comment https://github.com/torizon/meta-toradex-torizon/pull/167#issuecomment-2444041285 may be helpful as well.

**Comment by sergioprado** [comment]
> @sergioprado I imagine we can close this given the fix already referenced by @fboudra, right? Comment https://github.com/torizon/meta-toradex-torizon/pull/167#issuecomment-2444041285 may be helpful as well.

I would say so, but since this is on `meta-toradex-torizon`, it is up to its maintainers to take the final decision. :-)

**Pull request closed without merging**
