### PR TITLE
rac: enable DBus client by default

### PR DESCRIPTION
**Pull request by EdTheBearded**
Related-to: TOR-3637

### CODE REVIEW

**Comment by EdTheBearded** [comment]
> Just checking, do we not need to update the `rac` recipe as well? I saw on the respective `rac` PR that we may need to update the packaging: [torizon/rac#20](https://github.com/torizon/rac/pull/20)
> 
> Actually wait that PR isn't even merged yet it seems. Or maybe I'm misunderstanding the connection between these.

Yup, you're right!
I thought by now this would've been merged, but yeah, we would also need to bump de recipe.

I'll leave this PR in draft until it gets merged.

**Comment by EdTheBearded** [comment]
@jsrc27 RAC hash has been bumped as part of the monthly release: https://github.com/torizon/meta-toradex-torizon/pull/188
And since the release is now finished, we can go ahead with this MR \o/

**Review by jsrc27 — APPROVED** [review]
LGTM

**Review by rborn-tx — APPROVED** [review]
LGTM

**Pull request merged**
