### PR TITLE
Get rid of the unfinished rootfs protection implementation

### PR DESCRIPTION
**Pull request by rborn-tx**
This is a cleanup to help maintenance basically removing anything related to composefs (rootfs protection) since we don't intend to make such a feature available on kirkstone.

### CODE REVIEW

**Comment by rborn-tx** [comment]
@sergioprado Tagging you here just to let you know about this cleanup.

**Comment by EdTheBearded** [comment]
Nice!!
And just to understand, this cleanup is really only for Kirkstone, right?

**Comment by rborn-tx** [comment]
> And just to understand, this cleanup is really only for Kirkstone, right?

That's right. Btw I put the "(kirkstone)" string in all commits so we don't mistakenly cherry pick any of them to other branches :wink:.

**Comment by EdTheBearded** [comment]
Oh, one last question! Is this related to a ticket?
If yes, then I'd ask if you could add the `Related-to` stuff to the commit messaged.

**Comment by rborn-tx** [comment]
> Oh, one last question! Is this related to a ticket? If yes, then I'd ask if you could add the `Related-to` stuff to the commit messaged.

No, I haven't created a ticket for it.

**Review by jsrc27 — APPROVED** [review]
LGTM

**Pull request merged**
